control/urls.py
from django.urls import path
from control import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('modifTab/<str:app_name>/<str:model_name>/<int:pk>/eliminar/',views.eliminar_equipo,name='eliminar'),
    path('generate_qr/<str:app_name>/<str:model_name>/<int:pk>', views.generate_qr, name='generate_qr'),
    path('qr_page/<str:app_name>/<str:model_name>/<int:pk>', views.qr_page, name='qr_page'),
]

inventario_de_equipo/urls.py
from django.contrib import admin
from django.urls import path, include
#from inventario_de_equipo.views import home,agregado

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tablaPrincipal/', include('tablaPrincipal.urls')),
    path('',include('iniciar_sesion.urls')),
    path('',include('tablaCategorias.urls')),
    path('tablaComputo/',include('tablaComputo.urls')),
    path('',include('control.urls')),
]

tablaCategorias/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('principal/',views.tablaCate,name='principal'),
]

tablaComputo/urls.py
from django.urls import path
from tablaComputo import views
app_name = 'tablaComputo'
urlpatterns = [
    path('principalEqui/',views.lista_equipo,name='principalObjs'),
    path('agregarEqui/',views.crear_equipo,name='agregarEqui'),
    path('modifTabEqui/<int:pk>/editar/',views.editar_equipo,name='editarEqui'),
    path('detalles/<int:pk>', views.detalles, name='detalles'),
]

tablaPrincipal/urls.py
from django.urls import path
from tablaPrincipal import views
app_name = 'tablaPrincipal'
urlpatterns = [
    path('principalTel/',views.lista_equipo,name='principalObjs'),
    path('agregarTel/',views.crear_equipo,name='agregarTel'),
    path('modifTab/<int:pk>/editar/',views.editar_equipo,name='editarTel'),
    path('detalles/<int:pk>', views.detalles, name='detalles'),
]

tablaCategorias/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from tablaPrincipal.models import inventarioTel
from tablaComputo.models import equipoPcCom

@login_required
def tablaCate(request):  
    datoTel = inventarioTel.objects.last()
    datoPc= equipoPcCom.objects.last()
    fechaTel = datoTel.fecha.strftime('%Y-%m-%d') if datoTel and datoTel.fecha else "Sin fecha"
    fechaPc = datoPc.fecha.strftime('%Y-%m-%d') if datoPc and datoPc.fecha else "Sin fecha"
    return render(request, 'listaCategorias.html',{'fechaTel':fechaTel,'fechaPc':fechaPc})

tablaCategorias/templates/listaCategorias.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" initial-scale=1.0">
    <title>Lista de categorías</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/tablaCategorias/Pagina_principal.css' %}">
</head>
<body>
    <header id="titulo">
    <h1>Categorías</h1>    
    <form method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <button id="crear_producto" type="submit">Cerrar sesión</button>
    </form>    
    </header>
    <main id="principal_tabla_inventario">
        <table id="tabla_gral_de_inventario">
            <tr id="cabecera_de_tabla">
                <td>Categoría</td>
                <!--<td>Reportes</td> proximamente-->
                <td>Ultima actualizacion</td>
                <td>Departamento responsable</td>
                <td>Detalles</td> <!-- link -->
            </tr>
            <tr>
                <td>
                    Equipo de computo y comunicacion
                </td>
                <td>
                    {{fechaPc}}
                </td>
                <td>
                    Sistemas
                </td>
                <td>
                    <a href="{%url 'tablaComputo:principalObjs'%}">Ver detalles</a>
                </td>
            </tr>
            <tr>
                <td>
                    Equipo telefonico
                </td>
                <td>
                   {{ fechaTel }}
                </td>
                <td>
                    Sistemas
                </td>
                <td>
                    <a href="{%url 'tablaPrincipal:principalObjs'%}">Ver detalles</a>
                </td>
            </tr>
            <tr>
                <td>
                    Equipo de operaciones
                </td>
                <td>
                    <!-- insertar fecha -->
                </td>
                <td>
                    Operaciones
                </td>
                <td>
                    <a href="">Ver detalles</a>
                </td>
            </tr>
            <tr>
                <td>
                    Herramienta
                </td>
                <td>
                    <!-- inserte fecha -->
                </td>
                <td>
                    Varios departamentos
                </td>
                <td>
                    <a href="">Ver detalles</a>
                </td>
            </tr>
            <tr>
                <td>
                    Papelería
                </td>
                <td>
                    <!-- inserte fecha -->
                </td>
                <td>
                    varios departamentos
                </td>
                <td>
                    <a href="">Ver detalles</a>
                </td>
            </tr>
            <tr>
                <td>
                    Vehículos
                </td>
                <td>
                    <!-- inserte fecha -->
                </td>
                <td>
                    Operaciones
                </td>
                <td>
                    <a href="">Ver detalles</a>
                </td>
            </tr>
            <tr>
                <td>
                    Uniformes
                </td>
                <td>
                    <!-- inserte fecha -->
                </td>
                <td>
                    Almacen
                </td>
                <td>
                    <a href="">Ver detalles</a>
                </td>
            </tr>
            <tr>
                <td>
                    Muebles
                </td>
                <td>
                    <!-- inserte fecha -->
                </td>
                <td>
                    Varios departamentos
                </td>
                <td>
                    <a href="">Ver detalles</a>
                </td>
            </tr>
            <tr>
                <td>
                    Otros
                </td>
                <td>
                    <!-- inserte fecha -->
                </td>
                <td>
                    Varios departamentos
                </td>
                <td>
                    <a href="">Ver detalles</a>
                </td>
            </tr>
        </table>
    </main>
</body>
</html>
<!-- equipo de computo y comunicacion 
equipo telefonico
equipo de operaciones
herramienta
papelería
vehiculos
uniformes
muebles
otros-->