control/urls.py
from django.urls import path
from control import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('modifTab/<str:app_name>/<str:model_name>/<int:pk>/eliminar/',views.eliminar_equipo,name='eliminar'),
    path('generate_qr/<str:app_name>/<str:model_name>/<int:pk>', views.generate_qr, name='generate_qr'),
    path('qr_page/<str:app_name>/<str:model_name>/<int:pk>', views.qr_page, name='qr_page'),
]

inventario_de_equipo/urls.py
from django.contrib import admin
from django.urls import path, include
#from inventario_de_equipo.views import home,agregado

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tablaPrincipal/', include('tablaPrincipal.urls')),
    path('',include('iniciar_sesion.urls')),
    path('',include('tablaCategorias.urls')),
    path('tablaComputo/',include('tablaComputo.urls')),
    path('',include('control.urls')),
]

tablaPrincipal/urls.py
from django.urls import path
from tablaPrincipal import views
app_name = 'tablaPrincipal'
urlpatterns = [
    path('principalTel/',views.lista_equipo,name='principalObjs'),
    path('agregarTel/',views.crear_equipo,name='agregarTel'),
    path('modifTab/<int:pk>/editar/',views.editar_equipo,name='editarTel'),
    path('detalles/<int:pk>', views.detalles, name='detalles'),
]

tablaPrincipal/models.py
from django.db import models
from django.utils import timezone

class baseItem(models.Model):
    nombre = models.CharField(max_length=50)
    en_servicio= models.BooleanField()
    detalles= models.TextField()
    fecha=models.DateField(default=timezone.now)
    class Meta:
         abstract=True
    def __str__(self):
         return self.nombre

class inventarioTel(baseItem):
    nombre=None
    telefono = models.CharField(max_length=100)
    marca = models.CharField(max_length=40)
    email = models.CharField(max_length=100)
    contrasena_ingreso= models.CharField(max_length=100)
    propietario=models.TextField()
    imei=models.TextField()
    def __str__(self):
        return self.telefono

class operaciones(baseItem):
    cantidad=models.IntegerField()
    serie=models.CharField(max_length=50)

class herramienta(baseItem):
    cantidad=models.IntegerField()

class papeleria():
    nombre = models.CharField(max_length=50)
    cantidad=models.IntegerField()
    detalles=models.CharField(max_length=100)

class vehiculos(baseItem):
     pass

class uniformes(baseItem):
    cantidad=models.IntegerField()

class muebles(baseItem):
    pass

def otro(baseItem):
    cantidad=models.IntegerField()#por si hay

tablaPrincipal/forms.py
from django import forms
from .models import inventarioTel

class inventarioform(forms.ModelForm):
    class Meta:
        model = inventarioTel
        fields =['telefono', 'marca', 'email', 'en_servicio', 'detalles', 'contrasena_ingreso', 'propietario', 'imei']
        widgets = {
            'detalles': forms.Textarea(attrs={'class': 'borde'}),
            'propietario': forms.Textarea(attrs={'class': 'borde'}),
            'imei': forms.Textarea(attrs={'class': 'borde'}),
            'contrasena_ingreso': forms.PasswordInput(attrs={'class': 'password borde', 'placeholder': 'Contraseña'}),
            }

tablaPrincipal/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import inventarioTel
from .forms import inventarioform
from django.contrib.auth.decorators import login_required

@login_required
def lista_equipo(request):
    equipo = inventarioTel.objects.all().order_by('id')
    todos=equipo.count()
    return render(request, 'equiptel.html', {'equipos': equipo,'todos':todos})

@login_required
def crear_equipo(request):
    if request.method == "POST":
        form = inventarioform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tablaPrincipal:principalObjs')
    else:
        form = inventarioform()
    return render(request, 'agregarTel.html', {'form': form})
@login_required
def editar_equipo(request, pk):
    equipo = get_object_or_404(inventarioTel, pk=pk)
    if request.method == "POST":
        form = inventarioform(request.POST, instance=equipo)
        if form.is_valid():
            form.save()
            return redirect('tablaPrincipal:principalObjs')
    else:
        form = inventarioform(instance=equipo)
    return render(request, 'editarTel.html', {'form': form})

def detalles(request,pk):
    equipo = get_object_or_404(inventarioTel, pk=pk)
    return render(request, 'verTel.html',{'equipo': equipo})

tablaPrincipal/templates/agregarEquipo.html
<!DOCTYPE html>

{% load static %}
<html lang="es">
<head>
    <title>Agregar Equipo</title>
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/paraTodos.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Equipo.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
</head>
<body>
    <h1>Agregar Equipo</h1>
    <form method="post" class="formulario_general">
        {% csrf_token %}
        <p>
            <label for="{{ form.telefono.id_for_label }}">Teléfono:</label>
            <input type="text" class="borde" id="{{ form.telefono.id_for_label }}" name="{{ form.telefono.name }}"  autocomplete="off">
        </p>
        <p>
            <label for="{{ form.marca.id_for_label }}">Marca:</label>
            <input type="text" class="borde" id="{{ form.marca.id_for_label }}" name="{{ form.marca.name }}" autocomplete="off">
        </p>
        <p>
            <label for="{{ form.email.id_for_label }}">Email:</label>
            <input type="text"class="borde" id="{{ form.email.id_for_label }}" name="{{ form.email.name }}" autocomplete="off">
        </p>
        <p>
            <label for="{{ form.en_servicio.id_for_label }}">En servicio:</label>
            {{ form.en_servicio }}
        </p>
        <p>
            <label for="{{ form.contrasena_ingreso.id_for_label }}">Contraseña de ingreso:</label>
            {{ form.contrasena_ingreso }}
            <button type="button" id="togglePassword">
                <i class="fas fa-eye-slash"></i>
            </button>
            {{ form.contrasena_ingreso.errors }}
        </p>
         <p>
            <label for="{{ form.imei.id_for_label }}">IMEI:</label>
            {{form.imei}}
        </p>
        <p>
            <label for="{{ form.detalles.id_for_label }}">Detalles:</label>
            {{form.detalles}}
        </p>
        <p>
            <label for="{{ form.propietario.id_for_label }}">Propietario:</label>
            {{form.propietario}}
        </p>
       
    <span class="botones">
        <button type="submit" class="regresar_actualizar">Guardar</button>
        <a href="{% url 'principalTel' %}" class="regresar_actualizar">Volver a la lista</a>
    </span>
    </form>
    
    <script src="{% static 'js/editar.js' %}" async></script>
</body>
</html>

tablaPrincipal/templates/agregarTel.html
<!DOCTYPE html>

{% load static %}
<html lang="es">
<head>
    <title>Agregar Equipo</title>
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/tablaPrincipal/paraTodos.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tablaPrincipal/Equipo.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
</head>
<body>
    <h1>Agregar Equipo Telefonico</h1>
    <form method="post" class="formulario_general">
        {% csrf_token %}
        <p>
            <label for="{{ form.telefono.id_for_label }}">Teléfono:</label>
            <input type="text" class="borde" id="{{ form.telefono.id_for_label }}" name="{{ form.telefono.name }}"  autocomplete="off">
        </p>
        <p>
            <label for="{{ form.marca.id_for_label }}">Marca:</label>
            <input type="text" class="borde" id="{{ form.marca.id_for_label }}" name="{{ form.marca.name }}" autocomplete="off">
        </p>
        <p>
            <label for="{{ form.email.id_for_label }}">Email:</label>
            <input type="text"class="borde" id="{{ form.email.id_for_label }}" name="{{ form.email.name }}" autocomplete="off">
        </p>
        <p>
            <label for="{{ form.en_servicio.id_for_label }}">En servicio:</label>
            {{ form.en_servicio }}
        </p>
        <p>
            <label for="{{ form.contrasena_ingreso.id_for_label }}">Contraseña de ingreso:</label>
            {{ form.contrasena_ingreso }}
            <button type="button" id="togglePassword">
                <i class="fas fa-eye-slash"></i>
            </button>
            {{ form.contrasena_ingreso.errors }}
        </p>
         <p>
            <label for="{{ form.imei.id_for_label }}">IMEI:</label>
            {{form.imei}}
        </p>
        <p>
            <label for="{{ form.detalles.id_for_label }}">Detalles:</label>
            {{form.detalles}}
        </p>
        <p>
            <label for="{{ form.propietario.id_for_label }}">Propietario:</label>
            {{form.propietario}}
        </p>
       
    <span class="botones">
        <button type="submit" class="regresar_actualizar">Guardar</button>
        <a href="{% url 'tablaPrincipal:principalObjs' %}" class="regresar_actualizar">Volver a la lista</a>
    </span>
    </form>
    
    <script src="{% static 'js/tablaPrincipal/editar.js' %}"></script>
</body>
</html>

tablaPrincipal/templates/editar.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <title>Editar Producto</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/paraTodos.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Equipo.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
</head>
<body>
    <h1>Editar Producto</h1>
    <form method="post" class="formulario_general">
        {% csrf_token %}
        <p>
            <label for="{{ form.telefono.id_for_label }}">Teléfono:</label>
            <input type="text" class="borde" id="{{ form.telefono.id_for_label }}" name="{{ form.telefono.name }}" value="{{form.telefono.value}}" autocomplete="off">
        </p>
        <p>
            <label for="{{ form.marca.id_for_label }}">Marca:</label>
            <input type="text" class="borde" id="{{ form.marca.id_for_label }}" name="{{ form.marca.name }}" value="{{form.marca.value}}" autocomplete="off">
        </p>
        <p>
            <label for="{{ form.email.id_for_label }}">Email:</label>
            <input type="text" class="borde" id="{{ form.email.id_for_label }}" name="{{ form.email.name }}" value="{{form.email.value}}" autocomplete="off">
        </p>
        <p>
            <label for="{{ form.en_servicio.id_for_label }}">En servicio:</label>
            {{ form.en_servicio }}
        </p>
        <p class="password-container">
            <label for="{{ form.contrasena_ingreso.id_for_label }}">Contraseña de ingreso:</label>
            <input type="password" id=" {{ form.contrasena_ingreso.id_for_label }}" class="password borde" name="{{ form.contrasena_ingreso.name }}"value="{{form.contrasena_ingreso.value}}" placeholder="Contraseña">
            <button type="button" id="togglePassword">
                <i class="fas fa-eye-slash"></i> <!-- Ojo cerrado al principio -->
            </button>
        </p>
        <p>
            <label for="{{ form.imei.id_for_label }}">IMEI:</label>
            {{form.imei}}
        </p>
        <p>
            <label for="{{ form.detalles.id_for_label }}">Detalles:</label>
            {{form.detalles}}
        </p>
        
        <p>
            <label for="{{ form.propietario.id_for_label }}">Propietario:</label>
            {{form.propietario}}
        </p>
        <span class="botones">
            <button type="submit" class="regresar_actualizar">Actualizar</button>
            <a class="regresar_actualizar" href="{% url 'principalTel' %}">Volver a la lista</a>
        </span>
    </form>
    <script src="{% static 'js/editar.js' %}" async></script>
</body>
</html>

tablaPrincipal/templates/editarTel.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <title>Editar Producto</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/tablaPrincipal/paraTodos.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tablaPrincipal/Equipo.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
</head>
<body>
    <h1>Editar Producto</h1>
    <form method="post" class="formulario_general">
        {% csrf_token %}
        <p>
            <label for="{{ form.telefono.id_for_label }}">Teléfono:</label>
            <input type="text" class="borde" id="{{ form.telefono.id_for_label }}" name="{{ form.telefono.name }}" value="{{form.telefono.value}}" autocomplete="off">
        </p>
        <p>
            <label for="{{ form.marca.id_for_label }}">Marca:</label>
            <input type="text" class="borde" id="{{ form.marca.id_for_label }}" name="{{ form.marca.name }}" value="{{form.marca.value}}" autocomplete="off">
        </p>
        <p>
            <label for="{{ form.email.id_for_label }}">Email:</label>
            <input type="text" class="borde" id="{{ form.email.id_for_label }}" name="{{ form.email.name }}" value="{{form.email.value}}" autocomplete="off">
        </p>
        <p>
            <label for="{{ form.en_servicio.id_for_label }}">En servicio:</label>
            {{ form.en_servicio }}
        </p>
        <p class="password-container">
            <label for="{{ form.contrasena_ingreso.id_for_label }}">Contraseña de ingreso:</label>
            <input type="password" id=" {{ form.contrasena_ingreso.id_for_label }}" class="password borde" name="{{ form.contrasena_ingreso.name }}"value="{{form.contrasena_ingreso.value}}" placeholder="Contraseña">
            <button type="button" id="togglePassword">
                <i class="fas fa-eye-slash"></i> <!-- Ojo cerrado al principio -->
            </button>
        </p>
        <p>
            <label for="{{ form.imei.id_for_label }}">IMEI:</label>
            {{form.imei}}
        </p>
        <p>
            <label for="{{ form.detalles.id_for_label }}">Detalles:</label>
            {{form.detalles}}
        </p>
        
        <p>
            <label for="{{ form.propietario.id_for_label }}">Propietario:</label>
            {{form.propietario}}
        </p>
        <span class="botones">
            <button type="submit" class="regresar_actualizar">Actualizar</button>
            <a class="regresar_actualizar" href="{% url 'tablaPrincipal:principalObjs' %}">Volver a la lista</a>
        </span>
    </form>
    <script src="{% static 'js/tablaPrincipal/editar.js' %}"></script>
</body>
</html>

tablaPrincipal/templates/equipcom.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" initial-scale=1.0">
    <title>Equipos telefonicos</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/Pagina_principal.css' %}">
</head>
<body>
    <header id="titulo">
    <h1>Inventario general de equipos de computo</h1>    
    <a id="crear_producto" href="{%url 'agregar'%}">Crear equipo</a>    
    <a id="crear_producto" href="{%url 'principal'%}">Regresar a categorias</a>    
    </header>
    <main id="principal_tabla_inventario">
        <table id="tabla_gral_de_inventario">
            <tr id="cabecera_de_tabla">
                <td>Teléfono</td>
                <td>Marca</td>
                <td>Email</td>
                <td>Está en servicio</td>
                <td>Detalles</td>
                <td>Propietario</td>
                <td>Imei</td>
                <td>Editar</td>
                <td>Eliminar</td>
                <td>Ver código <br>QR</td>
                
            </tr>
            {% for equipo in equipos %}
            <tr>
                <td>{{equipo.telefono}}</td>
                <td>{{equipo.marca}}</td>
                <td>{{equipo.email}}</td>
                {% if equipo.en_servicio is True%}
                <td>Si está en servicio</td>
                {% else %}
                <td>No está en servicio</td>
                {%endif%}
                <td>{{equipo.detalles}}</td>
                <td>{{equipo.propietario}}</td>
                <td>{{equipo.imei}}</td>
                <td class="editarEliminar"> <a href="{% url 'editar' equipo.pk %}">Editar</a></td>
                <td class="editarEliminar"> <a href="{% url 'eliminar' equipo.pk %}">Eliminar</a></td>
                <td class="editarEliminar"> <a href="{% url 'qr_page' equipo.pk %}">Ver QR</a></td>
            </tr>
            {% endfor %}
        </table>
    </main>
    <footer>
    </footer>
   
</body>
</html>
<!--agregar botón de exportar a excel-->
<!--agregar página de inicio de sesión y tabla de usuarios-->

tablaPrincipal/templates/equiptel.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" initial-scale=1.0">
    <title>Equipos telefonicos</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/tablaPrincipal/Pagina_principal.css' %}">
</head>
<body>
    <header id="titulo">
    <h1>Inventario general de equipos telefonicos</h1>    
    <a id="crear_producto" href="{%url 'tablaPrincipal:agregarTel'%}">Crear Producto</a>    
    <a id="crear_producto" href="{%url 'principal'%}">Regresar a categorias</a>    
    </header>
    <main id="principal_tabla_inventario">
        <table id="tabla_gral_de_inventario">
            <tr id="cabecera_de_tabla">
                <td>Teléfono</td>
                <td>Marca</td>
                <td>Email</td>
                <td>Está en servicio</td>
                <td>Detalles</td>
                <td>Propietario</td>
                <td>Imei</td>
                <td>Editar</td>
                <td>Eliminar</td>
                <td>Ver código <br>QR</td>
                
            </tr>
            {% for equipo in equipos %}
            <tr>
                <td>{{equipo.telefono}}</td>
                <td>{{equipo.marca}}</td>
                <td>{{equipo.email}}</td>
                {% if equipo.en_servicio is True%}
                <td>Si está en servicio</td>
                {% else %}
                <td>No está en servicio</td>
                {%endif%}
                <td>{{equipo.detalles}}</td>
                <td>{{equipo.propietario}}</td>
                <td>{{equipo.imei}}</td>
                <td class="editarEliminar"> <a href="{% url 'tablaPrincipal:editarTel' equipo.pk %}"><span class="material-symbols-outlined"> edit </span></a></td>
                <td class="editarEliminar"> <a href="{% url 'eliminar' app_name='tablaPrincipal' model_name='InventarioTel' pk=equipo.pk %}"><span class="material-symbols-outlined">delete</span></a></td>
                <td class="editarEliminar"> <a href="{% url 'qr_page' app_name='tablaPrincipal' model_name='InventarioTel' pk=equipo.pk %}"><span class="material-symbols-outlined">qr_code</span></a></td>
            </tr>
            {% endfor %}
        </table>
    </main>
    <footer>
        <p> Total: {{ todos }} </p>
    </footer>
   
</body>
</html>
<!--agregar botón de exportar a excel-->
<!--tablaPrincipal:url
modificar urls para poder realizar lo normal-->

tablaPrincipal/templates/inventario.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" initial-scale=1.0">
    <title>Productos</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/Pagina_principal.css' %}">
</head>
<body>
    <header id="titulo">
    <h1>Inventario general de productos</h1>    
    <a id="crear_producto" href="{%url 'agregar'%}">Crear Producto</a>
 
    </header>
    <main id="principal_tabla_inventario">
        
        <table id="tabla_gral_de_inventario">
            <tr id="cabecera_de_tabla">
                <td>Teléfono</td>
                <td>Marca</td>
                <td>Email</td>
                <td>Está en servicio</td>
                <td>Detalles</td>
                <td>Propietario</td>
                <td>Imei</td>
                <td>Editar</td>
                <td>Eliminar</td>
                <td>Ver código <br>QR</td>
                
            </tr>
            {% for equipo in equipos %}
            <tr>
                <td>{{equipo.telefono}}</td>
                <td>{{equipo.marca}}</td>
                <td>{{equipo.email}}</td>
                {% if equipo.en_servicio is True%}
                <td>Si está en servicio</td>
                {% else %}
                <td>No está en servicio</td>
                {%endif%}
                <td>{{equipo.detalles}}</td>
                <td>{{equipo.propietario}}</td>
                <td>{{equipo.imei}}</td>
                <td class="editarEliminar"> <a href="{% url 'editar' equipo.pk %}">Editar</a></td>
                <td class="editarEliminar"> <a href="{% url 'eliminar' equipo.pk %}">Eliminar</a></td>
                <td class="editarEliminar"> <a href="{% url 'qr_page' equipo.pk %}">Ver QR</a></td>
            </tr>
            {% endfor %}
        </table>
    </main>
    <footer>

    </footer>
   
</body>
</html>

tablaPrincipal/templates/qr_page.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página con Código QR</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/paraTodos.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/qrcode.css' %}">
</head>
<body id="codigo_qr_paginaPrincipal">
    <h1>Codigo qr generado</h1>
    <!-- Mostrar el código QR generado -->
    <div class="contenido">
        <a href="{% url 'generate_qrTel' equipo.pk %}"><img id="codigo_qr" src="{% url 'generate_qrTel' equipo.pk %}" alt="Código QR"></a>
        <span><a href="{% url 'principalTel' %}" class="regresar_actualizar ">Regresar a la categoría principal</a></span>
    </div>
</body>
</html>

<!--Agregar boton de imprimir qr-->

tablaPrincipal/templates/verTel.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tablaPrincipal/paraTodos.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tablaPrincipal/detalles.css' %}">
    <title>Document</title>
</head>
<body>
    <span class="detalles">
        <h1>Estos son los detalles <br> del equipo <br> {{equipo.marca}}</h1>
        <p><span> Teléfono:</span> {{equipo.telefono}}</p>
        <p><span>Marca:</span> {{equipo.marca}}</p>
        <p><span>Email:</span> {{equipo.email}}</p>
        {% if equipo.en_servicio is True%}
        <p><span>Está en servicio</span></p>
        {% else %}
        <p><span>No está en servicio</span></p>
        {%endif%}
        <p><span>Detalles:</span> {{equipo.detalles}}</p>
        <p><span>Propietario:</span> {{equipo.propietario}}</p>
        <p><span>IMEI:</span> {{equipo.imei}}</p>
    </span>
</body>
</html>