control/urls.py
from django.urls import path
from control import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('modifTab/<str:app_name>/<str:model_name>/<int:pk>/eliminar/',views.eliminar_equipo,name='eliminar'),
    path('generate_qr/<str:app_name>/<str:model_name>/<int:pk>', views.generate_qr, name='generate_qr'),
    path('qr_page/<str:app_name>/<str:model_name>/<int:pk>', views.qr_page, name='qr_page'),
]

inventario_de_equipo/urls.py
from django.contrib import admin
from django.urls import path, include
#from inventario_de_equipo.views import home,agregado

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tablaPrincipal/', include('tablaPrincipal.urls')),
    path('',include('iniciar_sesion.urls')),
    path('',include('tablaCategorias.urls')),
    path('tablaComputo/',include('tablaComputo.urls')),
    path('',include('control.urls')),
]

tablaComputo/urls.py
from django.urls import path
from tablaComputo import views
app_name = 'tablaComputo'
urlpatterns = [
    path('principalEqui/',views.lista_equipo,name='principalObjs'),
    path('agregarEqui/',views.crear_equipo,name='agregarEqui'),
    path('modifTabEqui/<int:pk>/editar/',views.editar_equipo,name='editarEqui'),
    path('detalles/<int:pk>', views.detalles, name='detalles'),
]

tablaComputo/models.py
from django.db import models

from django.utils import timezone
# Create your models here.

class baseItem(models.Model):
    propietario = models.CharField(max_length=50)
    en_servicio= models.BooleanField()
    detalles= models.TextField()
    fecha=models.DateField(default=timezone.now)
    class Meta:
         abstract=True
    def __str__(self):
         return self.nombre
class equipoPcCom(baseItem):
    marca= models.CharField(max_length=25)
    departamento=models.CharField(max_length=15)
    imei=models.CharField(max_length=50)
    contrasena_ingreso= models.CharField(max_length=100)

tablaComputo/forms.py
from django import forms
from .models import equipoPcCom

class inventarioform(forms.ModelForm):
    class Meta:
        model = equipoPcCom
        fields =['marca', 'departamento', 'imei', 'contrasena_ingreso', 'propietario', 'en_servicio', 'detalles']
        widgets = {
            'detalles': forms.Textarea(attrs={'class': 'borde'}),
            'propietario': forms.Textarea(attrs={'class': 'borde'}),
            'imei': forms.Textarea(attrs={'class': 'borde'}),
            'contrasena_ingreso': forms.PasswordInput(attrs={'class': 'password borde', 'placeholder': 'Contraseña'}),
            }

tablaComputo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import equipoPcCom
from .forms import inventarioform
from django.contrib.auth.decorators import login_required

@login_required
def lista_equipo(request):
    equipo = equipoPcCom.objects.all().order_by('id')
    todos=equipo.count()
    return render(request, 'equipcom.html', {'equipos': equipo,'todos':todos})

@login_required
def crear_equipo(request):
    if request.method == "POST":
        form = inventarioform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tablaComputo:principalObjs')
    else:
        form = inventarioform()
    return render(request, 'agregarEquipo.html', {'form': form})
@login_required
def editar_equipo(request, pk):
    equipo = get_object_or_404(equipoPcCom, pk=pk)
    if request.method == "POST":
        form = inventarioform(request.POST, instance=equipo)
        if form.is_valid():
            form.save()
            return redirect('tablaComputo:principalObjs')
    else:
        form = inventarioform(instance=equipo)
    return render(request, 'editarEquipo.html', {'form': form})

def detalles(request,pk):
    equipo = get_object_or_404(equipoPcCom, pk=pk)
    return render(request, 'verEquipo.html',{'equipo': equipo})

tablaComputo/templates/agregarEquipo.html
<!DOCTYPE html>

{% load static %}
<html lang="es">
<head>
    <title>Agregar Equipo</title>
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/tablaComputo/paraTodos.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tablaComputo/Equipo.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
</head>
<body>
    <h1>Agregar Equipo</h1>
    <form method="post" class="formulario_general">
        {% csrf_token %}
        <p>
            <label for="{{ form.marca.id_for_label }}">Marca</label>
            <input type="text" class="borde" id="{{ form.marca.id_for_label }}" name="{{ form.marca.name }}"  autocomplete="off">
        </p>
        <p>
            <label for="{{ form.departamento.id_for_label }}">Departamento:</label>
            <input type="text" class="borde" id="{{ form.departamento.id_for_label }}" name="{{ form.departamento.name }}" autocomplete="off">
        </p>
        <p>
            <label for="{{ form.imei.id_for_label }}">IMEI:</label>
            <input type="text"class="borde" id="{{ form.imei.id_for_label }}" name="{{ form.imei.name }}" autocomplete="off">
        </p>
        <p>
            <label for="{{ form.contrasena_ingreso.id_for_label }}">Contraseña de ingreso:</label>
            {{ form.contrasena_ingreso }}
            <button type="button" id="togglePassword">
                <i class="fas fa-eye-slash"></i>
            </button>
            {{ form.contrasena_ingreso.errors }}
        </p>
        <p>
            <label for="{{ form.en_servicio.id_for_label }}">En servicio:</label>
            {{ form.en_servicio }}
        </p>
        <p>
            <label for="{{ form.propietario.id_for_label }}">Propietario:</label>
            {{form.propietario}}
        </p>
        <p>
            <label for="{{ form.detalles.id_for_label }}">Detalles:</label>
            {{form.detalles}}
        </p>
        <p></p>
    <span class="botones">
        <button type="submit" class="regresar_actualizar">Guardar</button>
        <a href="{% url 'tablaComputo:principalObjs' %}" class="regresar_actualizar">Volver a la lista</a>
    </span>
    </form>
    
    <script src="{% static 'js/tablaComputo/editar.js' %}"></script>
</body>
</html>

tablaComputo/templates/editarEquipo.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <title>Editar Producto</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/tablaComputo/paraTodos.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tablaComputo/Equipo.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
</head>
<body>
    <h1>Editar Producto</h1>
    <form method="post" class="formulario_general">
        {% csrf_token %}
        <p>
            <label for="{{ form.marca.id_for_label }}">Marca:</label>
            <input type="text" class="borde" id="{{ form.marca.id_for_label }}" name="{{ form.marca.name }}" value="{{form.marca.value}}" autocomplete="off">
        </p>
        <p>
            <label for="{{ form.departamento.id_for_label }}">Departamento:</label>
            <input type="text" class="borde" id="{{ form.departamento.id_for_label }}" name="{{ form.departamento.name }}" value="{{form.departamento.value}}" autocomplete="off">
        </p>
        <p>
            <label for="{{ form.imei.id_for_label }}">IMEI:</label>
            <input type="text"class="borde" id="{{ form.imei.id_for_label }}" name="{{ form.imei.name }}" value="{{form.imei.value}}" autocomplete="off">
        </p>
        <p class="password-container">
            <label for="{{ form.contrasena_ingreso.id_for_label }}">Contraseña de ingreso:</label>
            <input type="password" id=" {{ form.contrasena_ingreso.id_for_label }}" class="password borde" name="{{ form.contrasena_ingreso.name }}"value="{{form.contrasena_ingreso.value}}" placeholder="Contraseña">
            <button type="button" id="togglePassword">
                <i class="fas fa-eye-slash"></i> <!-- Ojo cerrado al principio -->
            </button>
        </p>
        <p>
            <label for="{{ form.en_servicio.id_for_label }}">En servicio:</label>
            {{ form.en_servicio }}
        </p>
        
        <p>
            <label for="{{ form.propietario.id_for_label }}">Propietario:</label>
            {{form.propietario}}
        </p>
        <p>
            <label for="{{ form.detalles.id_for_label }}">Detalles:</label>
            {{form.detalles}}
        </p>
        <p class="vacio"></p>
        <span class="botones">
            <button type="submit" class="regresar_actualizar">Actualizar</button>
            <a class="regresar_actualizar" href="{% url 'tablaComputo:principalObjs' %}">Volver a la lista</a>
        </span>
    </form>
    <script src="{% static 'js/tablaComputo/editar.js' %}"></script>
</body>
</html>

tablaComputo/templates/equipcom.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" initial-scale=1.0">
    <title>Equipos de computo</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/tablaComputo/Pagina_principal.css' %}">
</head>
<body>
    <header id="titulo">
    <h1>Inventario general de equipos de computo</h1>    
    <a id="crear_producto" href="{%url 'tablaComputo:agregarEqui'%}">Crear equipo</a>    
    <a id="crear_producto" href="{%url 'principal'%}">Regresar a categorias</a>    
    </header>
    <main id="principal_tabla_inventario">
        <table id="tabla_gral_de_inventario">
            <tr id="cabecera_de_tabla">
                <td>Marca</td> 
                <td>Está en servicio</td>
                <td>Detalles</td>
                <td>Departamento</td>
                <td>Propietario</td>
                <td>imei</td>
                <td>Editar</td>
                <td>Eliminar</td>
                <td>Ver QR</td>  
            </tr>
            {% for equipo in equipos %}
            <tr>
                <td>{{equipo.marca}}</td>
                {% if equipo.en_servicio is True%}
                <td>Si está en servicio</td>
                {% else %}
                <td>No está en servicio</td>
                {%endif%}
                <td>{{equipo.detalles}}</td>
                <td>{{equipo.departamento}}</td>
                <td>{{equipo.propietario}}</td>
                <td>{{equipo.imei}}</td>
                <td class="editarEliminar"> <a href="{% url 'tablaComputo:editarEqui' equipo.pk %}"><span class="material-symbols-outlined"> edit </span></a></td>
                <td class="editarEliminar"> <a href="{% url 'eliminar' app_name='tablaComputo' model_name='equipoPcCom' pk=equipo.pk %}"><span class="material-symbols-outlined">delete</span></a></td>
                <td class="editarEliminar"> <a href="{% url 'qr_page' app_name='tablaComputo' model_name='equipoPcCom' pk=equipo.pk %}"><span class="material-symbols-outlined">qr_code</span></a></td>
            </tr>
            {% endfor %}
        </table>
    </main>
    <footer>
        <p> Total: {{ todos }} </p>
    </footer>
   
</body>
</html>
<!--agregar botón de exportar a excel-->
<!--agregar página de inicio de sesión y tabla de usuarios-->

tablaComputo/templates/verEquipo.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tablaComputo/paraTodos.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tablaComputo/detalles.css' %}">
    <title>Document</title>
</head>
<body>
    <span class="detalles">
        <h1>Estos son los detalles<br> del equipo <br>{{equipo.marca}}</h1>
        <p><span> Departamento:</span> {{equipo.departamento}}</p>
        {% if equipo.en_servicio is True%}
        <p><span>El equipo está en servicio</span></p>
        {% else %}
        <p><span>El equipo no está en servicio</span></p>
        {%endif%}
        <p><span>Detalles:</span> {{equipo.detalles}}</p>
        <p><span>Propietario:</span> {{equipo.propietario}}</p>
        <p><span>IMEI:</span> {{equipo.imei}}</p>
    </span>
</body>
</html>